
[functions.crear-preferencia]
enabled = true
verify_jwt = false
import_map = "./functions/crear-preferencia/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crear-preferencia/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crear-preferencia/*.html" ]

[functions.webhook-pago]
enabled = true
verify_jwt = false
import_map = "./functions/webhook-pago/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/webhook-pago/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/webhook-pago/*.html" ]

[functions.mp-oauth]
enabled = true
verify_jwt = false
import_map = "./functions/mp-oauth/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mp-oauth/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mp-oauth/*.html" ]

[functions.crear-pago-stripe]
enabled = true
verify_jwt = false
import_map = "./functions/crear-pago-stripe/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/crear-pago-stripe/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/crear-pago-stripe/*.html" ]

[functions.stripe-connect-onboarding]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-connect-onboarding/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-connect-onboarding/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-connect-onboarding/*.html" ]
